
 

# Site settings
title: Skalas
header-img: img/home-bg.jpg
email: escalas5@gmail.com
description: "Miguel Escalante, mathematician, developer, data scientist, data engineer, whovian."
baseurl: ""
url: "http://Skalas.github.io"
twitter_username: Skalas
github_username:  Skalas
facebook_username:  Skalas
instagram_username: Skalas
linkedin_url: skalas
gp_username: MiguelAngelEscalante

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems:	 
  - jekyll-redirect-from
  - jekyll-paginate
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
